### ISSUE TITLE
bad texture sizes

### ISSUE THREAD

**Issue by rabbitchemicals** [ProfessorFichte/Additional-RPG-Jewelry#4]
some of the textures are 12x12 when they should be 16x16

![wolf_school_medallion](https://github.com/user-attachments/assets/c4e93a49-d85d-4d5c-9337-ff4cad96c20e)
![bear_school_medallion](https://github.com/user-attachments/assets/33d8a7f6-af63-432c-9469-d5d28bd81db8)
![griffin_school_medallion](https://github.com/user-attachments/assets/9eb7e4e7-ca93-4619-b9ce-cbabaedfd99e)
![cat_school_medallion](https://github.com/user-attachments/assets/6935010b-16ac-466f-b68a-bd9a4a2291c0)

**Comment by ProfessorFichte** [comment]
Hi! Is this causing any issues or bugs? The chosen texture size was intentional, because it looked better than 16x16, In my other Mods I also have some 24x24 weapon textures. Let me know if it caused errors/bugs etc.
Ingame I dont recognise something thats off
![image](https://github.com/user-attachments/assets/1f400a7c-2ddd-484b-b870-84677ef26507)

**Comment by rabbitchemicals** [comment]
... alrighty then. you do you
